use kendb;
insert into category values (null,"Rice All You Can");
insert into category values (null,"Appetizer");
insert into category values (null,"Short Order");
insert into category values (null,"Pork Specialties");
insert into category values (null,"Soup");
insert into category values (null,"Fish");
insert into category values (null,"Dessert");
insert into category values (null,"Drinks");
insert into category values (null,"Home Made Fresh Juice");