use kendb;
insert into product values (null,'Chicken Inasal',99,1,0);
insert into product values (null,'Grilled Pork Belly',109,1,0);
insert into product values (null,'Grilled Baby Back Ribs',139,1,0);
insert into product values (null,'Tuna Kinilaw',135,2,0);
insert into product values (null,'Pork Sisig',160,2,0);
insert into product values (null,'Chicharon Bulaklak',130,2,0);
insert into product values (null,'Pork Siomai',45,2,0);
insert into product values (null,'Dumplings - Pork',55,2,0);
insert into product values (null,'Dumplings - Chicken',55,2,0);
insert into product values (null,'Lumpia Ubod',60,2,0);
insert into product values (null,'Sotanghon Guisado - Chicken',165,3,0);
insert into product values (null,'Sotanghon Guisado - Pork',165,3,0);
insert into product values (null,'Sotanghon Guisado - Seafood',180,3,0);
insert into product values (null,'Pancit Guisado - Chicken',145,3,0);
insert into product values (null,'Pancit Guisado - Pork',145,3,0);
insert into product values (null,'Pancit Guisado - Seafood',160,3,0);
insert into product values (null,'Bihon Guisado - Chicken',145,3,0);
insert into product values (null,'Bihon Guisado - Pork',145,3,0);
insert into product values (null,'Bihon Guisado - Seafood',160,3,0);
insert into product values (null,'Bam-i - Chicken',165,3,0);
insert into product values (null,'Bam-i - Pork',165,3,0);
insert into product values (null,'Bam-i - Seafood',180,3,0);
insert into product values (null,'Mix Vegetables - Chicken',165,3,0);
insert into product values (null,'Mix Vegetables - Pork',165,3,0);
insert into product values (null,'Mix Vegetables - Seafood',165,3,0);
insert into product values (null,'Crispy Pata',375,4,0);
insert into product values (null,'Patatim',375,4,0);
insert into product values (null,'Grilled Baby Back Ribs Platter',550,4,0);
insert into product values (null,'Native Chicken Binakol',329,5,0);
insert into product values (null,'Native Chicken Tinola',299,5,0);
insert into product values (null,'Seafood Sinigang',139,5,0);
insert into product values (null,'Seafood Tinola',139,5,0);
insert into product values (null,'Steamed Tilapia',175,6,0);
insert into product values (null,'Grilled Tuna Belly',190,6,0);
insert into product values (null,'Steamed Pompano',360,6,0);
insert into product values (null,'Leche Flan Small',30,7,0);
insert into product values (null,'Leche Flan Big',95,7,0);
insert into product values (null,'Maja Blanca',25,7,0);
insert into product values (null,'Fruit Salad',45,7,0);
insert into product values (null,'Macaroni',45,7,0);
insert into product values (null,'Coke',18,8,0);
insert into product values (null,'Sprite',18,8,0);
insert into product values (null,'Royal',18,8,0);
insert into product values (null,'Pineapple Juice',45,8,0);
insert into product values (null,'PineOrange Juice',45,8,0);
insert into product values (null,'Four Seasons Juice',45,8,0);
insert into product values (null,'Camote Juice',22,9,0);
insert into product values (null,'Tanglad',22,9,0);